Fixes issue-1455 MetricRegistryListener should be invoked before adding meter to the registry
dropwizard/metrics pull request #1457
Opened 2019-07-14 01:58 UTC by asarkar

Each `on*Added` method returns a meter corresponding to the one passed in, making it possible to wrap/proxy a meter before it's added to the registry. A common use case for this is interoperability with another metrics library.

Also got rid of `MetricRegistryListener.Base` since we can use `default` methods in Java 8+, and don't need an `abstract` adapter class.

Added unit tests.

2019-07-14 02:09 UTC, asarkar commented
Seems like `codeclimate` check is failing on existing code, and in a way that doesn't make sense.

2019-10-31 06:07 UTC, baharclerode commented
How do you handle when a listener is added _after_ some metrics have already been added to the registry? It looks like you ignore the return result form the listener.... which creates a weird behavior in that the return value of the listener may or may not actually be used, and there's no way for the listener to know.

Similar with `register()` and `registerAll()`.... both of these allow an application to pass in a metric that they've already created and are using. The listeners wouldn't be able to wrap these either.

2019-10-31 06:38 UTC, asarkar commented
@baharclerode How’s the case of adding a listener after adding a metrics handled in the existing code?

2019-10-31 14:46 UTC, baharclerode commented
Currently, when you add a listener, it is invoked for all existing metrics already added to the listener. This ensures that any listener registered with a `MetricRegistry` always knows about every metric in the registry: https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L367-L369

This greatly simplifies the API usage / avoids timing issues about when metrics are registered vs when listeners are registered.

2019-12-07 11:40 UTC, joschi requested changes
@asarkar Thanks for your contribution!

In general I like the PR with some minor change requests and questions.

2019-12-07 11:40 UTC, joschi commented on metrics-core/src/test/java/com/codahale/metrics/MetricRegistryListenerTest.java
> +                .isEqualTo(gauge);
Shouldn't it use the `isSameAs()` annotation to match the test name?

2019-12-07 11:40 UTC, joschi commented on metrics-core/src/test/java/com/codahale/metrics/MetricRegistryListenerTest.java
> +                .isEqualTo(counter);
Shouldn't it use the `isSameAs()` annotation to match the test name?

2019-12-07 11:40 UTC, joschi commented on metrics-core/src/test/java/com/codahale/metrics/MetricRegistryListenerTest.java
> +                .isEqualTo(histogram);
Shouldn't it use the `isSameAs()` annotation to match the test name?

2019-12-07 11:40 UTC, joschi commented on metrics-core/src/test/java/com/codahale/metrics/MetricRegistryListenerTest.java
>      public void noOpsOnMeterAdded() {
Could we make the test names consistent?

2019-12-07 11:40 UTC, joschi commented on metrics-core/src/test/java/com/codahale/metrics/MetricRegistryListenerTest.java
>      public void noOpsOnTimerAdded() {
Could we make the test names consistent?

2019-12-07 11:40 UTC, joschi commented on metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
> +            return null;
Why don't we return the `Gauge<?>` which has been passed into the method when it was added?

2019-12-07 11:40 UTC, joschi commented on metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
> +            return null;
Why don't we return the `Counter` which has been passed into the method when it was added?

2019-12-07 11:40 UTC, joschi commented on metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
> +            return null;
Why don't we return the `Histogram` which has been passed into the method when it was added?

2019-12-07 11:40 UTC, joschi commented on metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
> +            return null;
Why don't we return the `Meter` which has been passed into the method when it was added?

2019-12-07 11:40 UTC, joschi commented on metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
> +            return null;
Why don't we return the `Timer` which has been passed into the method when it was added?

2019-12-07 11:40 UTC, joschi commented
@asarkar Please rebase this PR on the current `4.1-development` branch. Thanks!

2019-12-07 16:03 UTC, baharclerode commented
How do you control the order in which listeners are invoked? Previously this did not matter since listeners can't modify the metrics when they're added, but now they can so order is important/matters. It is often difficult to control all the points where listeners are added (some may be added by bundles, some may be added by the application code itself, some may be added dymanically at runtime, etc., which makes it difficult to control.

I'm still curious how you plan to handle adding a listener after metrics are already added to the registry. Right now it means that listeners have two different behaviors, and there's no way to know which will be used-- which makes for a very bad API.

IMHO the proper way to achieve what you're looking for is to create a separate metric registry B, install a metric listener into registry A, and wrap all the metrics before adding them to registry B, and then expose registry B however you want; Or subclass the `MetricRegistry` and override `register(String,T)` to wrap all metrics as they're added. Changing `MetricListener` into `MetricMutator` is a bad design choice.

2019-12-07 16:28 UTC, baharclerode commented
I'm actually also curious about this:

> A common use case for this is interoperability with another metrics library.

How does this help interoperability with another metrics library? Wrapping a metric when it is added to the registry does not, for example, allow you to reliably intercept calls or method invocations on that metric, or know when that metric has been updated.

You would actually need a pretty massive overhaul of all of the current metrics to support something like that (each metric would have to have it's own listener type); Even with wrapped metrics, the best you can do right now is poll the metrics periodically and export their aggregate state to another metrics library, which can be done with the existing `MetricListener` API.

2020-05-14 06:35 UTC, joschi commented
@dropwizard/metrics @dropwizard/committers How should we continue with this branch?

2020-05-14 06:57 UTC, closed without merging