Use logger rather than System.err
dropwizard/metrics pull request #1504
Opened 2019-11-05 12:56 UTC by Matzz

Use logger instead of System.err for logging ScheduledExecutorService termination failure.
Also added info log if ScheduledExecutorService was shut down successfully.

I think the current code use System.err because this piece was copied from java documentation:
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html
```
The following method shuts down an ExecutorService in two phases, first by calling shutdown to reject incoming tasks, and then calling shutdownNow, if necessary, to cancel any lingering tasks:
 void shutdownAndAwaitTermination(ExecutorService pool) {
   pool.shutdown(); // Disable new tasks from being submitted
   try {
     // Wait a while for existing tasks to terminate
     if (!pool.awaitTermination(60, TimeUnit.SECONDS)) {
       pool.shutdownNow(); // Cancel currently executing tasks
       // Wait a while for tasks to respond to being cancelled
       if (!pool.awaitTermination(60, TimeUnit.SECONDS))
           System.err.println("Pool did not terminate");
     }
   } catch (InterruptedException ie) {
     // (Re-)Cancel if current thread also interrupted
     pool.shutdownNow();
     // Preserve interrupt status
     Thread.currentThread().interrupt();
   }
 }
```

2019-12-07 10:44 UTC, joschi requested changes

2019-12-07 10:44 UTC, joschi commented on metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
> +        return duration / durationFactor;                LOG.error("Exception thrown from {}#report. Exception was suppressed.", ScheduledReporter.this.getClass().getSimpleName(), ex);
Accidental copy & paste error?

2019-12-09 10:56 UTC, Matzz commented
@joschi Yes, that was c&p issue. Fixed in the last commit

2019-12-09 21:24 UTC, joschi approved these changes

2019-12-09 21:25 UTC, merged